# Generated by Django 5.2.17 on 2026-09-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
