# Generated by Django 5.2.17 on 2026-09-13 16:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('jazz', 'Jazz'), ('funk', 'Funk'), ('classical', 'Classical'), ('swing', 'Swing')], default='pop', max_length=20)),
                ('audio', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
