# Generated by Django 5.2.17 on 2026-09-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_project_url_project_tech_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnail',
            new_name='project_image_url',
        ),
    ]
